### ISSUE TITLE
Blazor Server?

### ISSUE THREAD

**Issue by mnidhk** [CrahunGit/BlazorComponents#1]
Is this Nuget also for Blazor Server?
I did installed the Nuget but when i insert the "@Using ..."  in _Imports it does not recognize "CrahunComponents"

**Comment by CrahunGit** [comment]
Yes. It’s for blazor server as well. It’s for blazor 5. Not working on 3.1

**Comment by mnidhk** [comment]
Thank you for your fast reply.
Aha, not working on 3.1. 
Not (easy) possible?

**Comment by CrahunGit** [comment]
The target is not net standard but i I’ll change it to be compatible with  3.1 i can

**Comment by mnidhk** [comment]
That would be awesome!

Can't go to .Net5 at this moment with several projects

**Comment by CrahunGit** [comment]
Sorry for the delay but currently I've no chance to downgrade the repo to 3.1 since few components will not work,. There is no js module import or inputfile in this version. 

Too much work just to have half of the components. Feel free to create a pull request with this changes if you want. I'll apreciate your efforts
